#workflow to automatically triggers a series of commands
#checks out the pushed code
#installs software dependencies
#runs bats -v

name: learn-github-actions
on: [push]
jobs: 
  check-bats-version: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: actions-setup-node@v1
      - run: npm install -g bats
      - run: bats -v
